version: 0.2

phases:
  build:
    commands:
      - echo "Changing into source directory $CODEBUILD_SRC_DIR"
      - echo "Installing dependencies into src file"
      - pip install -t /src -r requirements.txt
