version: 0.2

phases:
  build:
    commands:
      - echo "Building the Lambda functions..."
      - pwd
      - cd check
      - pwd 
      - ls
      - zip -r ../check.zip *
      - cd ..
      - ls
      - pwd

  post_build:
    commands:
      - pwd 
      - ls
      - echo "Updating the Lambda functions..."
      - aws lambda update-function-code --function-name check --zip-file "fileb://check.zip"
    
